server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:together
    username: jwt
    password:

  jpa:
    hibernate:
      ddl-auto: update #create update none
    show-sql: true